version: '3.8'
services:
  mongo:
      container_name: mongo
      image: mongo:latest
      ports:
        - 27020:27017
      env_file: .env
      environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      networks:
        - db_network

networks:
  db_network:
    external: true
  